version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord-image-hash-bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    restart: unless-stopped
    volumes:
      - ./data:/usr/src/app/data